### ISSUE TITLE
No CTCF, Nanog and Oct4 ChIP-seq for E14 cells in ENCODE

### ISSUE THREAD

**Issue by brainfo** [guifengwei/ChromHMM_mESC_mm10#4]
I didn't find them.
Anyone know where to find these data？
there are CTCF ChIP-seq dataset for ES-Bruce cells, are they the same as E14 cells?

**Comment by guifengwei** [comment]
> I didn't find them.
> Anyone know where to find these data？
> there are CTCF ChIP-seq dataset for ES-Bruce cells, are they the same as E14 cells?

Hi, there is the link for CTCF ChIP-seq from E14 cells.
https://www.encodeproject.org/biosamples/ENCBS705LKU/

**Comment by brainfo** [comment]
> > I didn't find them.
> > Anyone know where to find these data？
> > there are CTCF ChIP-seq dataset for ES-Bruce cells, are they the same as E14 cells?
> 
> Hi, there is the link for CTCF ChIP-seq from E14 cells.
> https://www.encodeproject.org/biosamples/ENCBS705LKU/

Thanks !!!!
